name: LionRenderer2D
attributes:
  ORGANIZATIONNAME: Lion Software Tomasz Lewandowski
options:
  createIntermediateGroups: true
  xcodeVersion: 11.3
  groupSortPosition: top
  deploymentTarget:
    iOS: "13.0"
    macOS: "10.15"
configs:
  Debug: debug
  Release: release
fileGroups:
  - Configurations
  - Package.swift
configFiles:
  Debug: Configurations/Debug.xcconfig
  Release: Configurations/Release.xcconfig
schemes:
  LionRenderer2D:
    build:
      targets:
        LionRenderer2D_iOS: all
        LionRenderer2D_tvOS: all
        LionRenderer2D_watchOS: all
        LionRenderer2D_macOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets: [LionRenderer2DTests]
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  LionRenderer2D:
    type: framework
    platform: [macOS, iOS, tvOS, watchOS]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(RENDERER_2D_BUNDLE_IDENTIFIER)
        PROVISIONING_PROFILE_SPECIFIER: $(RENDERER_2D_PROVISIONING_PROFILE_SPECIFIER)
    sources:
      - path: LionRenderer2D
  LionRenderer2DTests:
    type: bundle.unit-test
    platform: macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.lionsoftware.lionengine.2d.renderer.tests
        # empty specifier resolves to "Automatic"
        PROVISIONING_PROFILE_SPECIFIER: 
    sources:
      - path: LionRenderer2DTests
    dependencies:
      - target: LionRenderer2D_macOS
  Example:
    type: application
    platform: macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.lionsoftware.lionengine.2d.renderer.example
        # empty specifier resolves to "Automatic"
        PROVISIONING_PROFILE_SPECIFIER:
        CURRENT_PROJECT_VERSION: 1
    sources:
      - path: Example
      - path: ExampleCommon
    dependencies:
      - target: LionRenderer2D_macOS
    postBuildScripts:
      - script: |
                "${PODS_ROOT}/SwiftLint/swiftlint"
        name: SwiftLint